### PR TITLE
Add support for Node’s CommonJS module system

### PR DESCRIPTION
**Pull request by gasi**
Hello,

First of all, thanks for this awesome library.

I really needed this functionality in [Node](http://nodejs.org/), so added a couple of lines (/ht @aseemk) to make it compatible with the [CommonJS](http://www.commonjs.org/) [module system](http://wiki.commonjs.org/wiki/Modules/1.1).

I ran both `rake test:conformance` (251 tests of 307 passed, 56 failed) and `rake test` (23 tests of 23 passed, 0 failed) and got the same results before and after my changes.

I hope you guys accept this pull request and also publish this baby onto [npm](http://npmjs.org/).

Cheers,
Daniel

### CODE REVIEW

**Comment by ded** [comment]
it's already on npm. `npm install twitter-text`

**Comment by aseemk** [comment]
Interesting; it is. The version on npm seems to be clearly different from this one on GitHub though -- it has a package.json and it supports exports. Where is this source (other than in a tarball on npm's registry)? @gasi did this work because it wasn't obvious that you guys already had this. =) Thanks!

**Comment by ded** [comment]
Sorry for the confusion. That hidden tarball source is sitting on my computer — I figured as a Twitter employee that I could get away with publishing it myself.

It's currently separate than the main source only because we use this library for Twitter.com and I didn't want to cause confusion (or explain) why the `module.exports` is in the source.

Fwiw, the `twttr.txt` namespace is what's being exported. So you can use it as such:

``` js
var twitter = require('twitter-text')
$('#tweet').html(twitter.autoLink(twitter.htmlEscape(status.text)))
```

I'll add docs on the README so this is clear

**Comment by gasi** [comment]
Thanks for the clarification, @ded. I’d still encourage you to publish the source of the npm package or merge this pull request, so people have access to both, the browser and Node version of this library. What do you think?

**Pull request closed without merging**
