### PR TITLE
Add AMD support

### PR DESCRIPTION
**Pull request by jasontbradshaw**
This is a very small change that would make it easier for those of us using requirejs in our build process. Currently, we have to either create a dummy module that returns the global `twttr.txt` object, or do lots of ugly configuration to get it to play nice.

### CODE REVIEW

**Comment by jakl** [comment]
Sounds great, thanks!

**Comment by jasontbradshaw** [comment]
@jakl, what's the possibility of getting a version bump for this change?

Is that something I should submit as a PR, something that should be done on the master branch directly, or something else entirely?

**Comment by jakl** [comment]
Done!

**Comment by jasontbradshaw** [comment]
Thanks!

**Pull request merged**
