### PR TITLE
Modify tweet_length to count URL as 20/21 chars

### PR DESCRIPTION
**Pull request by keitaf**
This is based on the pull request https://github.com/twitter/twitter-text-js/pull/19

I modified it such that getTweetLength() counts HTTP or protocol-less URL as 20 characters and HTTPS URL as 21 characters.

### CODE REVIEW

**Comment by timhaines** [comment]
+1 Would love to see this merged.

**Comment by hoverbird** [comment]
This makes a lot of sense :). Shippit!

**Comment by timhaines** [comment]
Go on then!

**Comment by timhaines** [comment]
Woo hoo!  :-)

**Pull request merged**
