### PR TITLE
Add a function to calculate a Tweet's length, taking account for URLs.

### PR DESCRIPTION
**Pull request by maccman**

### CODE REVIEW

**Comment by howardr** [comment]
I support having a method like this in the core lib.  We use twitter-text-js on dozens of projects a month and use a very similar method to the one @maccman has made.

**Comment by howardr** [comment]
There is actually another pull request (issue #19) that has similar functionality.

**Comment by timhaines** [comment]
FWIW This patch identifies a t.co url when it has a / in it.  t.co/ is enough - or favstar.fm/ .  Just thought I'd mention this as I was only looking at t.co initially (without the /) and thinking it wasn't recognizing them.  This behavior seems okay, as Twitter.com doesn't recognized or count them as urls without the / either.

**Comment by caniszczyk** [comment]
Hey @keitaf can you comment on this?

**Comment by maccman** [comment]
Any updates on this?

**Comment by keitaf** [comment]
I merged https://github.com/twitter/twitter-text-js/pull/58, which introduced twttr.txt.getTweetLength() to calculate the length of tweets with URLs taken into account. So I'm closing this pull request. Sorry for taking it a long time.

**Pull request closed without merging**
